orange_dj_homepage:
    path:     /
    defaults: { _controller: OrangeDjBundle:Default:index }

orange_dj_contacts:
    path:     /contacts
    defaults: { _controller: OrangeDjBundle:Default:contacts }

orange_dj_articles:
    path:     /articles
    defaults: { _controller: OrangeDjBundle:Article:index }

orange_dj_article:
    path:     /articles
    defaults: { _controller: OrangeDjBundle:Article:view }
    requirements:
            page:  \d+

