parameters:
#    orange_dj.example.class: Orange\DjBundle\Example

services:
#    orange_dj.example:
#        class: %orange_dj.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    orange.twig.orange_extension:
        class: Orange\DjBundle\Twig\OrangeExtension
        tags:
            - { name: twig.extension }